export { Navbar } from './navbar'
export { HeroSection } from './hero-section'
export { Features } from './features'
export { HowItWorks } from './how-it-works'
export { Pricing } from './pricing'
export { CTA } from './cta'
export { Footer } from './footer'
export { ScrollReveal } from './scroll-reveal'
