// Ready-made knowledge base templates. Each template pre-fills a KB's name,
// description, and creates seed documents so users get a working KB immediately.

export type KnowledgeTemplateType =
  | 'product-docs'
  | 'faq-base'
  | 'company-wiki'
  | 'support-articles'

export interface KnowledgeTemplateDocument {
  name: string
  type: 'txt' | 'md' | 'csv' | 'json'
  content: string
}

export interface KnowledgeTemplate {
  id: KnowledgeTemplateType
  name: string
  description: string
  documents: KnowledgeTemplateDocument[]
}

const templates: Record<KnowledgeTemplateType, KnowledgeTemplate> = {
  'product-docs': {
    id: 'product-docs',
    name: 'Product Documentation',
    description: 'A structured knowledge base for product docs, API references, and guides.',
    documents: [
      {
        name: 'overview.md',
        type: 'md',
        content: [
          '# Product Overview',
          '',
          'Welcome to the Convio documentation. Convio is a platform for building, deploying, and managing AI agents that can interact with your customers, analyze data, and automate workflows.',
          '',
          '## Getting Started',
          '',
          'Follow these steps to create your first agent in under 10 minutes:',
          '',
          '1. **Create an account** — Sign up at app.convio.com. No credit card required.',
          '2. **Choose a template** — Browse our agent templates for common use cases like Customer Support, FAQ, or Tutor.',
          '3. **Connect knowledge** — Upload documents or connect a knowledge base so your agent has real context.',
          '4. **Configure the model** — Pick a model (GPT-4, GPT-4o-mini, Claude, etc.) and set temperature, reasoning effort, and system prompt.',
          '5. **Test and deploy** — Preview responses in the chat panel, then deploy via web widget, shareable link, API, or WhatsApp.',
          '',
          '## Core Concepts',
          '',
          '### Agents',
          'An agent is an AI-powered assistant configured with a system prompt, model, tools, and optional knowledge base. Agents can be deployed to multiple channels.',
          '',
          '### Knowledge Bases',
          'Knowledge bases give your agent domain-specific context. Upload documents in TXT, PDF, CSV, MD, or JSON format. Content is chunked, embedded, and stored for semantic retrieval at query time.',
          '',
          '### Tools',
          'Tools extend what your agent can do beyond text generation. Built-in tools include Web Search, Calculator, and URL Fetcher. External tools can be connected via MCP servers.',
          '',
          '### Deployments',
          'Deploy your agent to a web chat widget embedded on your site, a shareable public URL, via API endpoints, or to WhatsApp Business.',
          '',
          '## Key Features',
          '',
          '- **Multi-model support** — Use OpenAI, Anthropic, Google, or custom providers via BYOK',
          '- **RAG-powered answers** — Retrieval Augmented Generation using your knowledge base',
          '- **Streaming responses** — Real-time token-by-token streaming for a smooth chat experience',
          '- **Analytics** — Track conversations, satisfaction, token usage, and latency',
          '- **Team collaboration** — Invite team members, set roles, and manage org-level settings',
        ].join('\n'),
      },
      {
        name: 'api-reference.md',
        type: 'md',
        content: [
          '# API Reference',
          '',
          'This document describes the Convio REST API endpoints for programmatic access.',
          '',
          '## Authentication',
          '',
          'All API requests require an API key in the `Authorization` header:',
          '',
          '```',
          'Authorization: Bearer sk_eyJhbGciOiJIUzI1NiIs...',
          '```',
          '',
          'API keys are managed in Settings > API Keys. Each key has read/write or read-only permissions scoped to an organization.',
          '',
          '## Endpoints',
          '',
          '### Agents',
          '',
          '| Method | Path | Description |',
          '|--------|------|-------------|',
          '| GET | /organizations/:orgId/agents | List all agents |',
          '| POST | /organizations/:orgId/agents | Create a new agent |',
          '| GET | /agents/:id | Get agent details |',
          '| PATCH | /agents/:id | Update agent settings |',
          '| DELETE | /agents/:id | Delete an agent |',
          '| POST | /agents/:id/test | Test an agent message |',
          '',
          '### Knowledge Bases',
          '',
          '| Method | Path | Description |',
          '|--------|------|-------------|',
          '| GET | /organizations/:orgId/knowledge-bases | List all KBs |',
          '| POST | /organizations/:orgId/knowledge-bases | Create a KB |',
          '| GET | /knowledge-bases/:id | Get KB details |',
          '| PATCH | /knowledge-bases/:id | Update KB |',
          '| DELETE | /knowledge-bases/:id | Delete a KB |',
          '| POST | /knowledge-bases/:id/documents | Upload a document |',
          '| GET | /knowledge-bases/:id/documents | List documents |',
          '',
          '### Conversations',
          '',
          '| Method | Path | Description |',
          '|--------|------|-------------|',
          '| GET | /agents/:id/conversations | List conversations |',
          '| POST | /agents/:id/conversations | Start new conversation |',
          '| GET | /conversations/:id | Get conversation history |',
          '',
          '## Rate Limits',
          '',
          '- 100 requests per minute per API key',
          '- 500 requests per minute per organization',
          '- Burst limit: 200 requests in a 10-second window',
          '',
          'Rate limit headers are returned with every response:',
          '- `X-RateLimit-Limit` — Request limit for the current window',
          '- `X-RateLimit-Remaining` — Remaining requests in the current window',
          '- `X-RateLimit-Reset` — Unix timestamp when the window resets',
          '',
          'When exceeded, the API returns `429 Too Many Requests`.',
        ].join('\n'),
      },
      {
        name: 'troubleshooting.md',
        type: 'md',
        content: [
          '# Troubleshooting Guide',
          '',
          'Common issues and how to resolve them when using Convio.',
          '',
          '## Authentication Errors',
          '',
          '### 401 Unauthorized',
          'The API key is missing, invalid, or expired. Check that your API key is current and included in the Authorization header. Generate a new key from Settings > API Keys if needed.',
          '',
          '### 403 Forbidden',
          'The API key does not have permission for the requested resource. Verify that the key has the correct scope (read/write vs read-only) and belongs to the right organization.',
          '',
          '## Rate Limiting',
          '',
          '### 429 Too Many Requests',
          'You have exceeded the rate limit. Wait for the window to reset (check the X-RateLimit-Reset header). Consider implementing exponential backoff in your integration.',
          '',
          '## Server Errors',
          '',
          '### 500 Internal Server Error',
          'An unexpected error occurred. The request ID is included in the `X-Request-Id` response header — include this when contacting support.',
          '',
          '### 502 Bad Gateway / 503 Service Unavailable',
          'The service is temporarily unavailable. This usually resolves within a few minutes. Check status.convio.com for ongoing incidents.',
          '',
          '## Agent Issues',
          '',
          '### Agent responds with incorrect information',
          'Review the knowledge base content for accuracy. Check the model configuration — lower temperature (0.1-0.3) gives more deterministic answers. Ensure the system prompt provides clear instructions.',
          '',
          '### Streaming is slow or stuttering',
          'Check network connectivity. Large knowledge bases may take longer to retrieve context. Consider reducing the chunk size or limiting the number of chunks retrieved per query.',
          '',
          '### Knowledge base documents are stuck on "Processing"',
          'Documents in PDF format take longer to process. Files over 10MB may need additional time. If a document stays in "Processing" for more than 30 minutes, try re-uploading it.',
        ].join('\n'),
      },
    ],
  },
  'faq-base': {
    id: 'faq-base',
    name: 'FAQ Knowledge Base',
    description: 'A ready-to-use FAQ knowledge base with pre-built Q&A pairs.',
    documents: [
      {
        name: 'shipping.md',
        type: 'md',
        content: [
          '# Shipping & Delivery',
          '',
          '## Q: How long does standard shipping take?',
          'Standard shipping takes 3-5 business days within the continental US. Orders placed before 2 PM EST are shipped the same day. During holiday periods, delivery may take 5-7 business days.',
          '',
          '## Q: Do you offer express shipping?',
          'Yes, express shipping is available for an additional fee. Express orders arrive in 1-2 business days. Cutoff for express shipping is 2 PM EST. Weekend delivery is available in select areas.',
          '',
          '## Q: Do you ship internationally?',
          'Yes, we ship to over 50 countries including Canada, UK, EU member states, Australia, Japan, and Singapore. International orders typically take 7-14 business days. Customs processing may add additional time. Import duties and taxes are the responsibility of the recipient.',
          '',
          '## Q: How can I track my order?',
          'Once your order ships, you will receive a confirmation email with a tracking number and link. You can also check order status in your account dashboard under My Orders > Track Package. For real-time updates, enable push notifications in the mobile app.',
          '',
          '## Q: What if my package is lost or damaged?',
          'If your package is marked as delivered but you cannot locate it, contact us within 48 hours and we will initiate an investigation. For damaged items, take photos of the packaging and product, and reach out to our support team within 7 days for a replacement or refund.',
          '',
          '## Q: Can I change my shipping address after placing an order?',
          'Address changes can be made within 1 hour of placing the order. After that, the order may already be in fulfillment. Contact support immediately and we will do our best to accommodate the change.',
        ].join('\n'),
      },
      {
        name: 'returns.md',
        type: 'md',
        content: [
          '# Returns & Refunds',
          '',
          '## Q: What is your return policy?',
          'We offer a 30-day return policy for unused items in their original packaging. Returns are accepted within 30 days of delivery. Items must be in new, unused condition with all original tags, packaging, and accessories.',
          '',
          '## Q: How do I start a return?',
          'Log into your account, go to My Orders, select the item you want to return, and click "Return Item." You will receive a prepaid return shipping label via email. Drop the package at any authorized shipping location. Refunds are processed within 5-7 business days after we receive and inspect the returned item.',
          '',
          '## Q: Are there any items that cannot be returned?',
          'Yes, the following items are non-returnable: digital/downloadable products, gift cards, personalized items, and items marked as final sale. Perishable goods cannot be returned for health and safety reasons.',
          '',
          '## Q: Who pays for return shipping?',
          'Return shipping is free for defective or incorrect items. For standard returns, a flat fee of $5.95 is deducted from the refund amount. Expedited return shipping (with instant replacement) is available for a $12.95 fee.',
          '',
          '## Q: How long do refunds take to process?',
          'Once we receive your return, please allow 5-7 business days for inspection and processing. The refund will be issued to the original payment method. Credit card refunds may take an additional 3-5 business days to appear, depending on your card issuer. PayPal and Apple Pay refunds are typically instant.',
          '',
          '## Q: Can I exchange an item instead of returning it?',
          'Yes, exchanges are handled through the return process. Select the "Exchange" option when initiating a return. The replacement item ships once the return is scanned by the carrier. In-stock items are shipped immediately; out-of-stock items may take 5-10 business days.',
        ].join('\n'),
      },
      {
        name: 'payments.md',
        type: 'md',
        content: [
          '# Payments & Billing',
          '',
          '## Q: What payment methods do you accept?',
          'We accept Visa, Mastercard, American Express, Discover, PayPal, Apple Pay, Google Pay, and bank transfers (ACH) for US customers. Cryptocurrency payments are accepted through our Coinbase integration for select plans.',
          '',
          '## Q: Is my payment information secure?',
          'Yes, all payment data is encrypted using TLS 1.3. We are PCI DSS Level 1 compliant. Payment processing is handled by Stripe — we never store full credit card numbers on our servers. For added security, we support 3D Secure authentication.',
          '',
          '## Q: Can I cancel my subscription at any time?',
          'Yes, you can cancel anytime from Settings > Billing > Cancel Subscription. Your access continues through the end of the current billing period. No partial refunds are issued for mid-cycle cancellations. Cancelled accounts are downgraded to the free tier at the end of the billing cycle.',
          '',
          '## Q: How does billing work for teams?',
          'Team plans are billed monthly based on the number of active team members. You are charged for the maximum number of members during the billing period. Adding members mid-cycle results in a prorated charge. Removing members credits your account on the next invoice.',
          '',
          '## Q: Do you offer discounts for annual billing?',
          'Yes, annual billing gives you 2 months free compared to monthly billing. We also offer non-profit and educational discounts — contact our sales team with your documentation to apply. Volume pricing is available for teams of 25+ members.',
          '',
          '## Q: What happens if my payment fails?',
          'If a payment fails, we retry up to 3 times over 5 days. You will receive email notifications for each attempt. After 5 days, access is restricted until the payment is resolved. Your data is retained for 30 days after restriction. Reactivate anytime by updating your payment method and completing the payment.',
        ].join('\n'),
      },
    ],
  },
  'company-wiki': {
    id: 'company-wiki',
    name: 'Company Wiki',
    description: 'Internal knowledge base with company overview, policies, and team structure.',
    documents: [
      {
        name: 'about.md',
        type: 'md',
        content: [
          '# About Convio',
          '',
          '## Our Mission',
          'Convio exists to make AI accessible to every business. We believe that every company, regardless of size or technical expertise, should be able to build, deploy, and manage AI agents that serve their customers and teams.',
          '',
          '## Our Values',
          '',
          '### Customer First',
          'Every decision starts with the question: "Does this help our customers?" We ship features that solve real problems, not because they are trendy. Our support team responds within 2 hours during business hours.',
          '',
          '### Integrity',
          'We are transparent about what our AI can and cannot do. We never hallucinate capabilities in marketing. If an agent cannot answer something accurately, it says so. Customer data is never used to train public models.',
          '',
          '### Innovation',
          'We invest 40% of engineering time in research and experimentation. Our RAG pipeline is optimized for sub-500ms retrieval. We contribute to open-source AI tooling and publish our benchmarks publicly.',
          '',
          '### Transparency',
          'Internal dashboards are public to all employees. Engineering postmortems are shared company-wide. Every feature ships with documented known limitations. Quarterly OKRs and results are published on the company wiki.',
          '',
          '## History',
          'Convio was founded in 2023 by Bilal and a team of AI engineers who previously built customer support automation at a Fortune 500 company. The beta launched in March 2024 with 50 design partners. By December 2024, Convio powered over 100,000 conversations per month. As of 2025, we serve over 2,000 businesses across 30 countries.',
          '',
          '## Team',
          'We are a remote-first team of 45 people across 12 countries. Engineering is headquartered in Karachi, with additional hubs in Dubai, London, and Singapore. We have team members working across EMEA, APAC, and Americas timezones.',
        ].join('\n'),
      },
      {
        name: 'hr-policies.md',
        type: 'md',
        content: [
          '# HR Policies',
          '',
          '## Work Hours & Flexibility',
          'Standard working hours are 9 AM to 5 PM in your local timezone, with a 1-hour lunch break. We support flexible schedules — coordinate with your manager to adjust start/end times. Core overlap hours are 1 PM to 4 PM UTC for cross-timezone collaboration.',
          '',
          '## Time Off & Leave',
          '',
          '### Annual Leave',
          '- 20 paid days per year, accrued monthly',
          '- Unused leave carries forward up to 10 days',
          '- Leave requests must be submitted at least 3 days in advance (2 weeks for blocks of 5+ days)',
          '',
          '### Sick Leave',
          '- 10 paid sick days per year',
          '- No doctor note required for 1-2 day absences',
          '- Extended illness (3+ days) requires a medical certificate',
          '',
          '### Parental Leave',
          '- 16 weeks fully paid parental leave for primary caregivers',
          '- 6 weeks fully paid for secondary caregivers',
          '- Flexible return-to-work options including phased return over 4 weeks',
          '',
      '### Public Holidays',
      'You observe the public holidays of your country of residence. If a public holiday falls on your weekend, you may take the following Monday off.',
          '',
          '## Remote Work',
          'Convio is remote-first. You may work from anywhere with a reliable internet connection. All employees receive a one-time home office stipend of $1,500. Monthly internet reimbursement of $75 is included in your expense policy. Coworking space memberships are available on request.',
          '',
          'We host two company-wide offsites per year. Travel and accommodation are fully covered.',
          '',
          '## Performance Reviews',
          'Performance reviews happen twice a year (June and December). The process includes self-assessment, peer feedback, and manager evaluation. Promotions and compensation adjustments are aligned with review cycles.',
          '',
          '## Professional Development',
          'Each employee has an annual learning budget of $2,000 for courses, conferences, certifications, and books. We also run an internal mentorship program where senior team members pair with junior members for 3-month cycles.',
        ].join('\n'),
      },
      {
        name: 'tech-stack.md',
        type: 'md',
        content: [
          '# Technical Stack',
          '',
          'This document describes the technology choices across Convio\'s platform.',
          '',
          '## Frontend',
          '',
          '| Layer | Technology | Purpose |',
          '|-------|-----------|---------|',
          '| Framework | React 19 + TypeScript | UI components and pages |',
          '| Routing | React Router v7 | Client-side navigation |',
          '| Styling | Tailwind CSS v4 | Utility-first styling |',
          '| Components | shadcn/ui (Base UI React) | Accessible UI primitives |',
          '| State | TanStack Query v5 | Server state, caching |',
          '| Forms | React Hook Form + Zod | Form validation |',
          '| Build | Vite | Development server and bundling |',
          '',
          '## Backend',
          '',
          '| Layer | Technology | Purpose |',
          '|-------|-----------|---------|',
          '| Runtime | Node.js 22 | Server-side JavaScript |',
          '| Framework | Fastify v5 | High-performance HTTP server |',
          '| Database | PostgreSQL 16 | Primary data store |',
          '| ORM | Prisma v7 | Type-safe database access |',
          '| Auth | Supabase Auth | Authentication and JWT |',
          '| Validation | Zod | Request/response validation |',
          '| Queue | In-process | Document indexing jobs |',
          '',
          '## AI & Embeddings',
          '',
          '| Component | Technology | Purpose |',
          '|-----------|-----------|---------|',
          '| LLM Providers | OpenAI, Anthropic, Google | Text generation |',
          '| Embeddings | text-embedding-3-small | Document chunk vectors |',
          '| Vector Store | pgvector (PostgreSQL) | Similarity search |',
          '| Streaming | Server-Sent Events | Real-time chat responses |',
          '',
          '## DevOps',
          '',
          '| Component | Technology | Purpose |',
          '|-----------|-----------|---------|',
          '| Containerization | Docker | Consistent environments |',
          '| Orchestration | Railway | Deployment and scaling |',
          '| CI/CD | GitHub Actions | Automated testing and deploy |',
          '| Monitoring | Sentry | Error tracking and performance |',
          '| Storage | Supabase Storage | File uploads (avatars, PDFs) |',
        ].join('\n'),
      },
    ],
  },
  'support-articles': {
    id: 'support-articles',
    name: 'Support Articles',
    description: 'Pre-built support articles for helping users solve common problems.',
    documents: [
      {
        name: 'getting-started.md',
        type: 'md',
        content: [
          '# Getting Started with Convio',
          '',
          'This guide walks you through setting up your first AI agent from scratch.',
          '',
          '## Step 1: Create Your Account',
          'Visit app.convio.com and sign up with your email address or Google/ GitHub account. Verify your email and complete the onboarding questionnaire so we can recommend the best setup for your use case. No credit card is required for the free tier — you get 500 messages per month and 1 knowledge base.',
          '',
          '## Step 2: Create an Agent',
          'Click "New Agent" from the dashboard. Choose a template or start from scratch:',
          '',
          '- **Customer Support** — Handles common customer questions with empathy',
          '- **FAQ Assistant** — Answers frequently asked questions from your knowledge base',
          '- **Tutor** — Teaches concepts and checks understanding',
          '- **Custom** — Blank prompt for total control',
          '',
          'Give your agent a name and description. This helps team members understand what the agent is for.',
          '',
          '## Step 3: Connect a Knowledge Base',
          'Agents are only as good as the information they have access to. Create a knowledge base and upload your documents:',
          '',
          '- Supported formats: TXT, PDF, CSV, Markdown, JSON',
          '- Maximum file size: 10MB per file',
          '- Maximum documents per KB: 500 (Starter), 2000 (Pro), 10000 (Enterprise)',
          '',
      'Once uploaded, documents are processed and indexed. This takes a few seconds for text files and up to a minute for PDFs. You can start chatting with your agent immediately — it will use the indexed content to answer questions.',
          '',
          '## Step 4: Configure and Test',
          'Choose a model (GPT-4o-mini is recommended for most use cases). Set the temperature — lower values (0.1-0.3) give more precise answers, higher values (0.7-1.0) give more creative responses. Write a system prompt that defines your agent\'s personality, constraints, and goals.',
          '',
          'Use the test panel on the agent detail page to send sample messages and review responses. Iterate on the system prompt and knowledge base content based on what you see.',
          '',
          '## Step 5: Deploy',
          'When you are satisfied with the agent\'s responses, deploy it:',
          '',
          '- **Web Chat Widget** — Embed on your website with a script tag',
          '- **Shareable Link** — A public URL you can share with anyone',
          '- **API Access** — Integrate via REST API',
          '- **WhatsApp** — Connect to WhatsApp Business API',
          '',
          'Monitor conversations and satisfaction metrics from the analytics dashboard to continuously improve your agent.',
        ].join('\n'),
      },
      {
        name: 'data-sources.md',
        type: 'md',
        content: [
          '# Connecting Data Sources',
          '',
          'This guide covers how to add content to your knowledge base and best practices for optimal retrieval.',
          '',
          '## Supported Formats',
          '',
          '| Format | Extension | Use Case | Max Size |',
          '|--------|-----------|----------|----------|',
          '| Text | .txt | Plain text content, notes, transcripts | 10MB |',
          '| PDF | .pdf | Contracts, reports, scanned documents | 10MB |',
          '| Spreadsheet | .csv | Product catalogs, pricing tables, lists | 5MB |',
          '| Markdown | .md, .markdown | Documentation, articles, guides | 10MB |',
          '| JSON | .json | Structured data, API responses, configs | 5MB |',
          '',
          '## How Indexing Works',
          '',
          'When you upload a document, Convio processes it through several stages:',
          '',
          '1. **Extraction** — Text content is extracted from the file (OCR for PDFs, parsing for CSVs, etc.)',
          '2. **Chunking** — The extracted text is split into chunks of approximately 500 tokens with 100-token overlap',
          '3. **Embedding** — Each chunk is converted into a vector embedding using text-embedding-3-small',
          '4. **Storage** — Embeddings are stored in pgvector for similarity search',
          '',
          'When an agent receives a question, the query is embedded and the nearest chunks are retrieved from the vector store. The chunks are then included in the LLM prompt as context.',
          '',
          '## Best Practices',
          '',
          '### File Organization',
          '- Use clear, descriptive file names that reflect the content (e.g., `shipping-policy-2025.md` not `doc1.txt`)',
          '- Group related content into separate documents rather than one large file',
          '- Keep individual documents focused on a single topic for better retrieval accuracy',
          '',
          '### Content Quality',
          '- Use headings (H1, H2, H3) to structure content — this helps chunking produce meaningful segments',
          '- Write in complete sentences with context. Avoid isolated bullet points without explanation',
          '- Include examples and edge cases where possible',
          '- Update documents when policies change rather than adding new conflicting documents',
          '',
      '## URL Import',
      'You can also import content from public URLs. Convio fetches the page, extracts the main content, and indexes it. This is useful for importing documentation, blog posts, and public FAQs.',
        ].join('\n'),
      },
      {
        name: 'agent-setup.md',
        type: 'md',
        content: [
          '# Setting Up Your AI Agent',
          '',
          'A detailed walkthrough of agent configuration options and best practices.',
          '',
          '## Step 1: Choose a Template',
          'Convio provides pre-built templates that set sensible defaults for common use cases:',
          '',
          '- **Customer Support** — Handles complaints, questions, and escalations with empathy. Suggested model: GPT-4o-mini, temperature: 0.4',
          '- **Sales Representative** — Qualifies leads and highlights product value. Suggested model: GPT-4o, temperature: 0.7',
          '- **FAQ Assistant** — Answers knowledge-base questions concisely. Suggested model: GPT-4o-mini, temperature: 0.2',
          '- **Tutor** — Teaches concepts with patience and adaptive explanations. Suggested model: GPT-4o, temperature: 0.5',
          '- **Translator** — Translates between languages while preserving tone and intent. Suggested model: GPT-4o-mini, temperature: 0.3',
          '',
          'Each template configures the system prompt, model, temperature, and suggested tools automatically. You can customize everything after selecting a template.',
          '',
          '## Step 2: Write a System Prompt',
          'The system prompt is the most impactful setting. It defines the agent\'s behavior, constraints, and goals. A good system prompt includes:',
          '',
          '- **Role** — "You are a helpful customer support agent for Acme Corp"',
          '- **Rules** — "Never make promises about shipping dates. Always ask for the order number first."',
          '- **Tone** — "Respond in a warm, professional tone. Use the customer\'s name when available."',
          '- **Escalation** — "If the issue requires a refund over $100, escalate to a human agent."',
          '',
          'Keep the system prompt under 1500 characters for optimal model performance. Be specific rather than vague.',
          '',
          '## Step 3: Select Tools',
          'Tools extend your agent\'s capabilities beyond text generation:',
          '',
          '- **Web Search** — Searches the internet for current information. Useful for agents that need up-to-date data.',
          '- **Calculator** — Evaluates mathematical expressions. Useful for pricing and finance agents.',
          '- **URL Fetcher** — Reads content from a given URL. Useful for agents that reference web pages.',
          '- **Date & Time** — Gets the current date and time. Useful for scheduling and booking agents.',
          '',
          'You can also add custom tools via MCP (Model Context Protocol) servers. MCP tools are configured in Settings > MCP Servers.',
          '',
          '## Step 4: Configure Deployment',
          'Choose where your agent will be available:',
          '',
          '- **Web Chat Widget** — Embeddable JavaScript widget for your website. Customizable colors, position, and greeting message.',
          '- **Shareable Link** — A public URL that opens a chat interface. No integration required.',
          '- **API Access** — REST API endpoint for custom integrations. Full control over the chat experience.',
          '- **WhatsApp** — Connect to WhatsApp Business API. Requires a verified Meta Business account.',
          '',
          '## Step 5: Monitor and Improve',
          'After deployment, use the analytics dashboard to track:',
          '',
          '- **Conversation volume** — How many conversations are happening per day/week',
          '- **Satisfaction rate** — Thumbs up/down ratings from users',
          '- **Token usage** — Monthly token consumption for cost tracking',
          '- **Response latency** — Average time to first response',
          '',
          'Review conversations regularly to identify patterns, improve the system prompt, and update the knowledge base.',
        ].join('\n'),
      },
    ],
  },
}

/** Return a single template by type, or undefined if the type is unknown. */
export function getKnowledgeTemplate(type: string): KnowledgeTemplate | undefined {
  return templates[type as KnowledgeTemplateType]
}

/** Return all available knowledge base templates in a stable order. */
export function listKnowledgeTemplates(): KnowledgeTemplate[] {
  return Object.values(templates)
}