import {
  Home,
  Rocket,
  Users,
  Bot,
  Database,
  Wrench,
  MessageSquare,
  Handshake,
  Globe,
  Satellite,
  Key,
  Zap,
  BarChart3,
  Shield,
  CreditCard,
  Code,
  HelpCircle,
  BookOpen,
  type LucideIcon,
} from 'lucide-react'
import { WhatsAppIcon, TelegramIcon, DiscordIcon, SlackIcon } from './brand-icons'

export interface DocItem {
  title: string
  href: string
  icon: LucideIcon | React.ComponentType<{ className?: string }>
  description?: string
  soon?: boolean
  beta?: boolean
}

export interface DocSection {
  title: string
  items: DocItem[]
}

export const docSections: DocSection[] = [
  {
    title: 'Getting Started',
    items: [
      { title: 'Overview', href: '/docs', icon: Home },
      { title: 'What is Convio?', href: '/docs/what-is-convio', icon: Rocket },
      { title: 'Convio vs Others', href: '/docs/convio-vs-others', icon: BookOpen },
      { title: 'Creating an Account', href: '/docs/creating-account', icon: Rocket },
      { title: 'Dashboard Tour', href: '/docs/dashboard-tour', icon: Globe },
      { title: 'First Organization', href: '/docs/creating-organization', icon: Users },
      { title: 'Vocabulary', href: '/docs/vocabulary', icon: BookOpen },
    ],
  },
  {
    title: 'Organizations',
    items: [
      { title: 'Organizations', href: '/docs/organizations', icon: Users, beta: true },
      { title: 'Roles & Permissions', href: '/docs/roles', icon: Shield, beta: true },
      { title: 'Inviting Members', href: '/docs/inviting-members', icon: Users, beta: true },
      { title: 'Managing Members', href: '/docs/managing-members', icon: Users, beta: true },
      { title: 'Transfer Ownership', href: '/docs/transferring-ownership', icon: Users, beta: true },
      { title: 'Leaving an Org', href: '/docs/leaving-organization', icon: Users, beta: true },
      { title: 'Login Activity', href: '/docs/login-activity', icon: Shield, beta: true },
    ],
  },
  {
    title: 'AI Agents',
    items: [
      { title: 'What is an Agent?', href: '/docs/ai-agents', icon: Bot },
      { title: 'Creating an Agent', href: '/docs/creating-agent', icon: Bot },
      { title: 'AI Models', href: '/docs/ai-models', icon: Zap },
      { title: 'System Prompts', href: '/docs/system-prompts', icon: BookOpen },
      { title: 'Agent Settings', href: '/docs/agent-settings', icon: Wrench },
      { title: 'Welcome Messages', href: '/docs/welcome-messages', icon: MessageSquare },
      { title: 'Playground', href: '/docs/agent-playground', icon: Zap },
      { title: 'Agent Statuses', href: '/docs/agent-statuses', icon: Zap },
      { title: 'Cloning Agents', href: '/docs/cloning-agents', icon: Bot, soon: true },
    ],
  },
  {
    title: 'Knowledge Bases',
    items: [
      { title: 'What is a KB?', href: '/docs/what-is-knowledge-base', icon: Database },
      { title: 'Creating a KB', href: '/docs/creating-knowledge-base', icon: Database },
      { title: 'Document Types', href: '/docs/supported-documents', icon: BookOpen },
      { title: 'Uploading Docs', href: '/docs/uploading-documents', icon: Database },
      { title: 'Web Pages as Knowledge', href: '/docs/adding-web-pages', icon: Globe },
      { title: 'Document Processing', href: '/docs/document-processing', icon: Wrench },
      { title: 'Chunking', href: '/docs/understanding-chunking', icon: Wrench },
      { title: 'Vector Search', href: '/docs/vector-search', icon: Zap },
      { title: 'Reranking', href: '/docs/reranking', icon: Zap },
      { title: 'Document Statuses', href: '/docs/document-statuses', icon: Zap },
      { title: 'Managing KBs', href: '/docs/managing-knowledge-bases', icon: Database },
      { title: 'KB Templates', href: '/docs/knowledge-base-templates', icon: BookOpen },
    ],
  },
  {
    title: 'Tools & MCP',
    items: [
      { title: 'Tools Overview', href: '/docs/tools-overview', icon: Wrench },
      { title: 'Built-in Tools', href: '/docs/built-in-tools', icon: Zap },
      { title: 'Web Search', href: '/docs/web-search-tool', icon: Globe },
      { title: 'Calculator', href: '/docs/calculator-tool', icon: Code },
      { title: 'URL Fetcher', href: '/docs/url-fetcher-tool', icon: Globe },
      { title: 'Custom Tools', href: '/docs/custom-tools', icon: Wrench },
      { title: 'Attaching Tools', href: '/docs/attaching-tools', icon: Wrench },
      { title: 'What is MCP?', href: '/docs/mcp-overview', icon: Code },
      { title: 'MCP Server Types', href: '/docs/mcp-server-types', icon: Code },
      { title: 'Connect MCP Server', href: '/docs/connecting-mcp-server', icon: Code },
      { title: 'Link MCP to Agents', href: '/docs/linking-mcp-agents', icon: Code },
      { title: 'MCP Security', href: '/docs/mcp-security', icon: Shield },
    ],
  },
  {
    title: 'Conversations',
    items: [
      { title: 'Overview', href: '/docs/conversations', icon: MessageSquare },
      { title: 'Statuses', href: '/docs/conversation-statuses', icon: Zap },
      { title: 'Viewing', href: '/docs/viewing-conversations', icon: MessageSquare },
      { title: 'Reading Messages', href: '/docs/reading-messages', icon: MessageSquare },
      { title: 'Sending Messages', href: '/docs/sending-messages', icon: MessageSquare },
      { title: 'Message Streaming', href: '/docs/message-streaming', icon: Zap },
      { title: 'Metadata', href: '/docs/conversation-metadata', icon: Code },
      { title: 'Leads', href: '/docs/leads', icon: Users },
      { title: 'Resolving', href: '/docs/resolving-conversations', icon: Zap },
      { title: 'Search', href: '/docs/conversation-search', icon: BookOpen },
    ],
  },
  {
    title: 'Human Handoff',
    items: [
      { title: 'What is Handoff?', href: '/docs/human-handoff', icon: Handshake },
      { title: 'Handoff Triggers', href: '/docs/handoff-setup', icon: Zap },
      { title: 'Assigning', href: '/docs/assigning-conversations', icon: Users },
      { title: 'Agent Inbox', href: '/docs/agent-inbox', icon: MessageSquare },
      { title: 'Taking Over', href: '/docs/taking-over', icon: Handshake },
      { title: 'Returning to AI', href: '/docs/returning-to-ai', icon: Bot },
      { title: 'Notifications', href: '/docs/handoff-notifications', icon: Zap },
      { title: 'Best Practices', href: '/docs/handoff-best-practices', icon: BookOpen },
    ],
  },
  {
    title: 'Widgets',
    items: [
      { title: 'Web Widget', href: '/docs/web-widget', icon: Globe },
      { title: 'Creating a Widget', href: '/docs/creating-widget', icon: Globe },
      { title: 'Appearance', href: '/docs/widget-appearance', icon: Globe },
      { title: 'Allowed Domains', href: '/docs/allowed-domains', icon: Shield },
      { title: 'Settings', href: '/docs/widget-settings', icon: Wrench },
      { title: 'Embed (Script)', href: '/docs/embedding-script', icon: Code },
      { title: 'Embed (JS API)', href: '/docs/embedding-javascript', icon: Code },
      { title: 'Public API', href: '/docs/widget-public-api', icon: Code },
      { title: 'Testing', href: '/docs/testing-widget', icon: Zap },
      { title: 'Analytics', href: '/docs/widget-analytics', icon: BarChart3 },
      { title: 'Multi-language', href: '/docs/widget-multilang', icon: Globe },
      { title: 'Troubleshooting', href: '/docs/widget-troubleshooting', icon: HelpCircle },
    ],
  },
  {
    title: 'Deployments',
    items: [
      { title: 'Channels Overview', href: '/docs/channels', icon: Satellite },
      { title: 'Creating Deployment', href: '/docs/creating-deployment', icon: Satellite },
      { title: 'Statuses', href: '/docs/deployment-statuses', icon: Zap },
      { title: 'WhatsApp', href: '/docs/whatsapp-integration', icon: WhatsAppIcon },
      { title: 'WhatsApp (Twilio)', href: '/docs/whatsapp-twilio', icon: WhatsAppIcon },
      { title: 'WA Templates', href: '/docs/whatsapp-templates', icon: WhatsAppIcon },
      { title: 'Telegram', href: '/docs/telegram-integration', icon: TelegramIcon },
      { title: 'Discord', href: '/docs/discord-integration', icon: DiscordIcon },
      { title: 'Discord Gateway', href: '/docs/discord-gateway', icon: Code },
      { title: 'Slack', href: '/docs/slack-integration', icon: SlackIcon },
      { title: 'Testing', href: '/docs/testing-deployments', icon: Zap },
      { title: 'Managing', href: '/docs/managing-deployments', icon: Wrench },
      { title: 'Channel Behavior', href: '/docs/channel-behavior', icon: Globe },
    ],
  },
  {
    title: 'Provider Keys',
    items: [
      { title: 'What is BYOK?', href: '/docs/byok', icon: Key },
      { title: 'Supported Providers', href: '/docs/supported-providers', icon: Zap },
      { title: 'Adding a Key', href: '/docs/adding-provider-key', icon: Key },
      { title: 'Managing Keys', href: '/docs/managing-provider-keys', icon: Key },
      { title: 'Key Resolution', href: '/docs/key-resolution', icon: Code },
      { title: 'Available Models', href: '/docs/available-models', icon: Zap },
      { title: 'Mixing Providers', href: '/docs/using-different-providers', icon: Zap },
      { title: 'Local Models', href: '/docs/local-models', icon: Code },
      { title: 'Rate Limits', href: '/docs/rate-limits', icon: Shield },
      { title: 'Key Security', href: '/docs/api-key-security', icon: Shield },
    ],
  },
  {
    title: 'Automations',
    items: [
      { title: 'Overview', href: '/docs/automations', icon: Zap },
      { title: 'Broadcasts', href: '/docs/broadcasts', icon: MessageSquare },
      { title: 'Creating Broadcast', href: '/docs/creating-broadcast', icon: MessageSquare },
      { title: 'Managing Broadcasts', href: '/docs/managing-broadcasts', icon: Wrench },
      { title: 'Webhooks', href: '/docs/webhooks', icon: Code },
      { title: 'Webhook Events', href: '/docs/webhook-events', icon: Code },
      { title: 'Creating Webhook', href: '/docs/creating-webhook', icon: Code },
      { title: 'Webhook Security', href: '/docs/webhook-security', icon: Shield },
      { title: 'Testing Webhooks', href: '/docs/testing-webhooks', icon: Zap },
      { title: 'Retry Policy', href: '/docs/webhook-retry', icon: Zap },
      { title: 'Workflows', href: '/docs/webhook-workflows', icon: Zap },
    ],
  },
  {
    title: 'Analytics',
    items: [
      { title: 'Overview', href: '/docs/analytics', icon: BarChart3 },
      { title: 'Dashboard', href: '/docs/dashboard-analytics', icon: BarChart3 },
      { title: 'Per-Agent', href: '/docs/per-agent-analytics', icon: BarChart3 },
      { title: 'Key Metrics', href: '/docs/key-metrics', icon: Zap },
      { title: 'Channel Breakdown', href: '/docs/channel-breakdown', icon: Globe },
      { title: 'Date Ranges', href: '/docs/date-ranges', icon: Zap },
      { title: 'Success Rate', href: '/docs/success-rate', icon: Zap },
      { title: 'Token Tracking', href: '/docs/token-tracking', icon: Zap },
      { title: 'Audit Logs', href: '/docs/audit-logs', icon: Shield },
      { title: 'Exporting', href: '/docs/exporting-analytics', icon: Code },
    ],
  },
  {
    title: 'Security',
    items: [
      { title: 'Overview', href: '/docs/security', icon: Shield },
      { title: 'Moderation', href: '/docs/moderation', icon: Shield },
      { title: 'Profanity Filter', href: '/docs/profanity-filter', icon: Shield },
      { title: 'PII Detection', href: '/docs/pii-detection', icon: Shield },
      { title: 'Prompt Injection', href: '/docs/prompt-injection', icon: Shield },
      { title: 'Custom Rules', href: '/docs/custom-moderation', icon: Wrench },
      { title: 'Block-on-Violation', href: '/docs/block-on-violation', icon: Shield },
      { title: 'Audit Logs', href: '/docs/audit-logs-security', icon: Shield },
      { title: 'SSO', href: '/docs/sso', icon: Key },
      { title: 'Data Retention', href: '/docs/data-retention', icon: Database },
      { title: 'Data Management', href: '/docs/data-management', icon: Database },
      { title: 'Security Checklist', href: '/docs/security-checklist', icon: Shield },
    ],
  },
  {
    title: 'Billing',
    items: [
      { title: 'Plans', href: '/docs/plans', icon: CreditCard },
      { title: 'Feature Comparison', href: '/docs/plan-features', icon: BookOpen },
      { title: 'Usage Limits', href: '/docs/usage-limits', icon: Zap },
      { title: 'Viewing Plan', href: '/docs/viewing-plan', icon: CreditCard },
      { title: 'Upgrading', href: '/docs/upgrading-plan', icon: Zap },
      { title: 'Subscriptions', href: '/docs/managing-subscriptions', icon: CreditCard },
      { title: 'Invoices', href: '/docs/viewing-invoices', icon: CreditCard },
      { title: 'Customer Portal', href: '/docs/customer-portal', icon: Globe },
      { title: 'Usage Notifications', href: '/docs/usage-notifications', icon: Zap },
      { title: 'Enterprise', href: '/docs/enterprise-plans', icon: Users },
      { title: 'Canceling', href: '/docs/canceling-subscription', icon: Zap },
    ],
  },
  {
    title: 'API Reference',
    items: [
      { title: 'Overview', href: '/docs/api-overview', icon: Code, soon: true },
      { title: 'Authentication', href: '/docs/authentication', icon: Key, soon: true },
      { title: 'First Request', href: '/docs/first-api-request', icon: Code, soon: true },
      { title: 'Conventions', href: '/docs/api-conventions', icon: Code, soon: true },
      { title: 'Agents API', href: '/docs/api-agents', icon: Bot, soon: true },
      { title: 'Conversations API', href: '/docs/api-conversations', icon: MessageSquare, soon: true },
      { title: 'Messages API', href: '/docs/api-messages', icon: MessageSquare, soon: true },
      { title: 'KB API', href: '/docs/api-knowledge-bases', icon: Database, soon: true },
      { title: 'Streaming API', href: '/docs/streaming-api', icon: Zap, soon: true },
      { title: 'Webhook Events', href: '/docs/webhook-events-reference', icon: Code, soon: true },
      { title: 'Rate Limiting', href: '/docs/rate-limiting', icon: Shield, soon: true },
      { title: 'Error Codes', href: '/docs/error-codes', icon: HelpCircle, soon: true },
    ],
  },
  {
    title: 'Troubleshooting',
    items: [
      { title: 'Widget Not Loading', href: '/docs/widget-not-loading', icon: HelpCircle },
      { title: 'Agent Not Responding', href: '/docs/agent-not-responding', icon: HelpCircle },
      { title: 'KB Not Answering', href: '/docs/kb-not-answering', icon: HelpCircle },
      { title: 'Deployment Errors', href: '/docs/deployment-errors', icon: HelpCircle },
      { title: 'WhatsApp Issues', href: '/docs/whatsapp-issues', icon: HelpCircle },
      { title: 'Discord Issues', href: '/docs/discord-issues', icon: HelpCircle },
      { title: 'Telegram Issues', href: '/docs/telegram-issues', icon: HelpCircle },
      { title: 'Slack Issues', href: '/docs/slack-issues', icon: HelpCircle },
      { title: 'Streaming Issues', href: '/docs/streaming-not-working', icon: HelpCircle },
      { title: 'Billing Issues', href: '/docs/billing-issues', icon: HelpCircle },
      { title: 'Login Issues', href: '/docs/login-issues', icon: HelpCircle },
      { title: 'Performance', href: '/docs/performance-issues', icon: HelpCircle },
    ],
  },
  {
    title: 'FAQs',
    items: [
      { title: 'General', href: '/docs/faqs', icon: HelpCircle },
      { title: 'Technical', href: '/docs/technical-faqs', icon: HelpCircle },
      { title: 'Billing', href: '/docs/billing-faqs', icon: HelpCircle },
      { title: 'Security', href: '/docs/security-faqs', icon: HelpCircle },
    ],
  },
  {
    title: 'Best Practices',
    items: [
      { title: 'Overview', href: '/docs/best-practices', icon: BookOpen },
      { title: 'Prompt Engineering', href: '/docs/prompt-engineering', icon: Bot },
      { title: 'KB Best Practices', href: '/docs/kb-best-practices', icon: Database },
      { title: 'Multi-Channel', href: '/docs/multi-channel-strategy', icon: Globe },
      { title: 'Performance', href: '/docs/performance-optimization', icon: Zap },
      { title: 'Security', href: '/docs/security-best-practices', icon: Shield },
      { title: 'Cost Optimization', href: '/docs/cost-optimization', icon: CreditCard },
      { title: 'Agent Design', href: '/docs/agent-design-patterns', icon: Bot },
      { title: 'Conversation Design', href: '/docs/conversation-design', icon: MessageSquare },
    ],
  },
]
