import { Clock, Zap, TrendingUp, Users, MessageCircle, Target, ArrowRight } from 'lucide-react'
import { DocContent, DocPageHeader, DocCallout, DocFeatureCard, DocCardGrid, DocNextStepCard } from '@/components/docs'

export default function KeyMetricsPage() {
  return (
    <DocContent>
      <DocPageHeader
        breadcrumb={[
          { label: 'Documentation', href: '/docs' },
          { label: 'Key Metrics' },
        ]}
        title="Understanding Key Metrics"
        description="Definitions and benchmarks for the core metrics tracked across your Convio agents."
      />

      <h2 id="overview">Overview</h2>
      <p>
        Convio tracks several key metrics to help you evaluate agent performance, control costs, and improve user experience. This page explains what each metric means and how to interpret it.
      </p>

      <h2 id="avg-response-time">Average Response Time</h2>
      <p>
        The mean time between a user sending a message and the agent's first response. Measured in seconds.
      </p>
      <ul>
        <li><strong>Target:</strong> Under 3 seconds for chat channels</li>
        <li><strong>Includes:</strong> Model inference time, knowledge base lookup, tool execution</li>
        <li><strong>Excludes:</strong> Human agent response time (tracked separately)</li>
      </ul>
      <DocCallout variant="tip" icon={Clock} title="Improving response time">
        Use a faster model for simple FAQ agents. Cache frequent queries. Reduce knowledge base size by pruning low-quality documents.
      </DocCallout>

      <h2 id="token-usage">Token Usage</h2>
      <p>
        Tokens are the units AI models use to process text. Convio tracks two categories:
      </p>
      <DocCardGrid columns={2}>
        <DocFeatureCard
          icon={Zap}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Input Tokens"
          description="Tokens sent to the model: system prompt, knowledge base context, conversation history, and the user's message."
        />
        <DocFeatureCard
          icon={Zap}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Output Tokens"
          description="Tokens generated by the model in its response. Output tokens typically cost 2-4x more than input tokens."
        />
      </DocCardGrid>
      <p>
        Token usage directly determines your AI costs. Monitor both input and output tokens to optimize spending.
      </p>

      <h2 id="success-rate">Success Rate</h2>
      <p>
        The percentage of conversations resolved without human escalation. A conversation counts as successful when:
      </p>
      <ul>
        <li>The agent handled the full conversation</li>
        <li>The conversation reached Resolved status</li>
        <li>No handoff to a human agent occurred</li>
      </ul>
      <p>
        <strong>Target:</strong> 85%+ for well-configured agents. Below 70% indicates knowledge gaps or prompt issues.
      </p>

      <h2 id="user-satisfaction">User Satisfaction</h2>
      <p>
        Captured via the optional thumbs up/down feedback widget on agent responses. Calculated as:
      </p>
      <p>
        <code>(Thumbs up count) / (Total feedback submitted) x 100</code>
      </p>
      <p>
        Only conversations with feedback are counted. Low satisfaction often correlates with repetitive answers or misunderstanding user intent.
      </p>

      <h2 id="conversation-duration">Conversation Duration</h2>
      <p>
        The total time from the first user message to conversation resolution. Measured in minutes.
      </p>
      <ul>
        <li><strong>Short duration (less than 2 min):</strong> Quick FAQ resolution — ideal for simple queries</li>
        <li><strong>Medium duration (2-10 min):</strong> Normal support interaction</li>
        <li><strong>Long duration (more than 10 min):</strong> Complex issue or agent struggling — investigate</li>
      </ul>
      <DocCallout variant="warning" icon={Clock} title="Watch for outliers">
        Very long conversations often indicate the agent is stuck in a loop or unable to resolve the issue. Review conversations with duration over 15 minutes.
      </DocCallout>

      <h2 id="resolution-rate">Resolution Rate</h2>
      <p>
        Similar to success rate but includes human-assisted resolutions. Measures the percentage of conversations that eventually reach Resolved status, regardless of whether AI or a human handled them.
      </p>
      <ul>
        <li><strong>High resolution rate + high success rate:</strong> Agent is performing well</li>
        <li><strong>High resolution rate + low success rate:</strong> Agent needs human help often — improve knowledge base</li>
        <li><strong>Low resolution rate:</strong> Conversations are being abandoned, not resolved</li>
      </ul>

      <h2 id="benchmarks">Benchmarks</h2>
      <div className="overflow-x-auto my-6">
        <table className="w-full text-[13px] border-collapse">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Metric</th>
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Poor</th>
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Average</th>
              <th className="text-left py-2 font-heading font-semibold text-foreground">Good</th>
            </tr>
          </thead>
          <tbody className="text-muted-foreground">
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4">Response Time</td>
              <td className="py-2 pr-4">5s+</td>
              <td className="py-2 pr-4">2-5s</td>
              <td className="py-2">under 2s</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4">Success Rate</td>
              <td className="py-2 pr-4">under 70%</td>
              <td className="py-2 pr-4">70-85%</td>
              <td className="py-2">85%+</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4">User Satisfaction</td>
              <td className="py-2 pr-4">under 60%</td>
              <td className="py-2 pr-4">60-80%</td>
              <td className="py-2">80%+</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4">Resolution Rate</td>
              <td className="py-2 pr-4">under 80%</td>
              <td className="py-2 pr-4">80-92%</td>
              <td className="py-2">92%+</td>
            </tr>
            <tr>
              <td className="py-2 pr-4">Avg Duration</td>
              <td className="py-2 pr-4">15 min+</td>
              <td className="py-2 pr-4">5-15 min</td>
              <td className="py-2">under 5 min</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 id="next-steps">Next Steps</h2>
      <DocCardGrid columns={2}>
        <DocNextStepCard
          icon={TrendingUp}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Success Rate Deep Dive"
          href="/docs/success-rate"
        />
        <DocNextStepCard
          icon={Zap}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Token Tracking"
          href="/docs/token-tracking"
        />
      </DocCardGrid>
    </DocContent>
  )
}
