import { Link } from 'react-router-dom'
import { MessageSquare, Clock, Hash, User, Bot } from 'lucide-react'
import { DocContent, DocPageHeader, DocCallout, DocFeatureCard, DocCardGrid, DocNextStepCard } from '@/components/docs'

export default function ReadingMessagesPage() {
  return (
    <DocContent>
      <DocPageHeader
        breadcrumb={[
          { label: 'Documentation', href: '/docs' },
          { label: 'Reading Messages' },
        ]}
        title="Reading Messages"
        description="Understand how messages are displayed, what metadata is available, and how to interpret token usage and timing information."
      />

      <h2 id="message-history">Message History View</h2>
      <p>
        When you open a conversation, the message history displays all messages in chronological order. Each message bubble shows:
      </p>
      <ul>
        <li><strong>Sender:</strong> Whether the message is from the user or the agent</li>
        <li><strong>Content:</strong> The full text of the message (supports markdown rendering)</li>
        <li><strong>Timestamp:</strong> When the message was sent or received</li>
        <li><strong>Status:</strong> Delivery status — sent, delivered, or read (channel-dependent)</li>
      </ul>

      <h3 id="message-types">Message Types</h3>
      <div className="overflow-x-auto my-6">
        <table className="w-full text-[13px] border-collapse">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Type</th>
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Indicator</th>
              <th className="text-left py-2 font-heading font-semibold text-foreground">Description</th>
            </tr>
          </thead>
          <tbody className="text-muted-foreground">
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4 font-medium text-foreground">User Message</td>
              <td className="py-2 pr-4">Left-aligned, primary background</td>
              <td className="py-2">Incoming message from the end user</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4 font-medium text-foreground">Agent Message</td>
              <td className="py-2 pr-4">Right-aligned, card background</td>
              <td className="py-2">Response generated by the AI agent</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4 font-medium text-foreground">System Message</td>
              <td className="py-2 pr-4">Center-aligned, muted text</td>
              <td className="py-2">Status changes, escalations, internal notes</td>
            </tr>
            <tr>
              <td className="py-2 pr-4 font-medium text-foreground">Tool Call</td>
              <td className="py-2 pr-4">Collapsed block, expandable</td>
              <td className="py-2">Agent invoked a tool — shows tool name and result</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 id="timestamps">Timestamps and Metadata</h2>
      <p>
        Every message carries metadata that helps you understand the conversation flow:
      </p>
      <ul>
        <li><strong>Sent At:</strong> The exact time the message was sent (user) or generation started (agent)</li>
        <li><strong>Received At:</strong> When the message was delivered to the recipient</li>
        <li><strong>Read At:</strong> When the message was seen (WhatsApp, Telegram — not available on all channels)</li>
        <li><strong>Latency:</strong> Time between the user's message and the agent's first token response</li>
      </ul>

      <DocCallout variant="info" icon={Clock} title="Timezone display">
        Timestamps are displayed in your local timezone by default. Hover over any timestamp to see the UTC time.
      </DocCallout>

      <h2 id="token-usage">Token Usage Per Message</h2>
      <p>
        Each agent message includes token usage data. This helps you understand cost and model behavior:
      </p>
      <ul>
        <li><strong>Prompt Tokens:</strong> Tokens used from the conversation context and system prompt</li>
        <li><strong>Completion Tokens:</strong> Tokens generated in the agent's response</li>
        <li><strong>Total Tokens:</strong> Sum of prompt and completion tokens</li>
        <li><strong>Estimated Cost:</strong> Calculated based on your model's per-token pricing</li>
      </ul>

      <h3 id="viewing-token-details">Viewing Token Details</h3>
      <p>
        Click the token count badge on any agent message to expand the detailed breakdown. This shows:
      </p>
      <ul>
        <li>Exact token counts for prompt and completion</li>
        <li>The model used for that specific response</li>
        <li>Temperature setting at the time of generation</li>
        <li>Whether tools were called during generation</li>
      </ul>

      <DocCallout variant="tip" icon={Hash} title="Cost tracking">
        Token costs are aggregated at the conversation level and displayed in the conversation metadata panel. See <Link to="/docs/conversation-metadata" className="text-primary hover:underline">Conversation Metadata</Link> for details.
      </DocCallout>

      <h2 id="user-vs-assistant">User vs Assistant Messages</h2>
      <p>
        The conversation view clearly distinguishes between user and assistant messages:
      </p>
      <div className="rounded-lg border border-border/60 bg-card p-4 my-4 space-y-3">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <User className="h-3.5 w-3.5 text-primary" />
            <p className="text-[12px] font-heading font-semibold text-foreground">User Message</p>
          </div>
          <p className="text-[12px] text-muted-foreground">Always appears on the left. Contains the raw text the user typed or sent via their channel. No processing or modification is applied to the display.</p>
        </div>
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Bot className="h-3.5 w-3.5 text-success" />
            <p className="text-[12px] font-heading font-semibold text-foreground">Assistant Message</p>
          </div>
          <p className="text-[12px] text-muted-foreground">Always appears on the right. Contains the AI-generated response. May include markdown formatting, code blocks, or structured content. Token usage is displayed alongside.</p>
        </div>
      </div>

      <h2 id="scrolling">Scrolling and Pagination</h2>
      <p>
        Conversations with many messages use virtual scrolling. The most recent messages load first, and older messages load as you scroll up. This keeps the interface fast even for conversations with hundreds of messages.
      </p>

      <ul>
        <li>Messages load in batches of 50</li>
        <li>A loading indicator appears at the top while older messages load</li>
        <li>The conversation automatically scrolls to the bottom when new messages arrive</li>
        <li>Click the "Jump to latest" button to return to the bottom after scrolling up</li>
      </ul>

      <h2 id="next-steps">Next Steps</h2>
      <DocCardGrid columns={2}>
        <DocNextStepCard
          icon={MessageSquare}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Sending Messages"
          href="/docs/sending-messages"
        />
        <DocNextStepCard
          icon={Clock}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Message Streaming"
          href="/docs/message-streaming"
        />
      </DocCardGrid>
    </DocContent>
  )
}
