import { Zap, ArrowRight, TrendingUp, DollarSign, BarChart3, Bot, AlertTriangle } from 'lucide-react'
import { DocContent, DocPageHeader, DocCallout, DocFeatureCard, DocCardGrid, DocNextStepCard } from '@/components/docs'

export default function TokenTrackingPage() {
  return (
    <DocContent>
      <DocPageHeader
        breadcrumb={[
          { label: 'Documentation', href: '/docs' },
          { label: 'Token Tracking' },
        ]}
        title="Token Usage Tracking"
        description="Monitor AI costs, track input vs output tokens, and analyze usage per agent."
      />

      <h2 id="overview">Overview</h2>
      <p>
        Token usage is the primary driver of AI costs. Convio tracks every token consumed across all agents, channels, and conversations. This page explains how to read and optimize token usage.
      </p>

      <h2 id="monitoring-costs">Monitoring AI Costs</h2>
      <p>
        Your token usage is displayed in the analytics dashboard under <strong>Token Usage</strong>. It shows:
      </p>
      <ul>
        <li><strong>Total tokens:</strong> Combined input and output tokens for the selected period</li>
        <li><strong>Estimated cost:</strong> Dollar estimate based on your configured model pricing</li>
        <li><strong>Usage trend:</strong> Daily token consumption over time</li>
      </ul>

      <DocCallout variant="tip" icon={DollarSign} title="Set up cost alerts">
        Configure token usage alerts in <strong>Settings → Billing</strong> to get notified when daily or monthly usage exceeds your threshold. This prevents surprise bills from runaway conversations.
      </DocCallout>

      <h2 id="input-vs-output">Input vs Output Tokens</h2>
      <DocCardGrid columns={2}>
        <DocFeatureCard
          icon={Zap}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Input Tokens"
          description="Tokens sent to the model. Includes system prompt, knowledge base context, conversation history, and the user's message. Typically cheaper per token."
        />
        <DocFeatureCard
          icon={Zap}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Output Tokens"
          description="Tokens generated by the model. Typically cost 2-4x more than input tokens. Longer responses = higher output token cost."
        />
      </DocCardGrid>

      <h3 id="input-breakdown">Input Token Breakdown</h3>
      <ul>
        <li><strong>System prompt:</strong> Fixed cost per conversation — optimize prompt length</li>
        <li><strong>Knowledge base context:</strong> Variable — depends on retrieved chunks</li>
        <li><strong>Conversation history:</strong> Grows with conversation length</li>
        <li><strong>User message:</strong> Minimal — usually under 100 tokens</li>
      </ul>

      <h2 id="per-agent">Per-Agent Breakdown</h2>
      <p>
        View token usage per agent in the analytics dashboard:
      </p>
      <ul>
        <li>Select an agent from the dropdown to see its specific token consumption</li>
        <li>Compare agents side by side using the Compare view</li>
        <li>Identify agents with unusually high token usage per conversation</li>
      </ul>

      <div className="overflow-x-auto my-6">
        <table className="w-full text-[13px] border-collapse">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Agent</th>
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Conversations</th>
              <th className="text-left py-2 pr-4 font-heading font-semibold text-foreground">Avg Tokens/Conv</th>
              <th className="text-left py-2 font-heading font-semibold text-foreground">Est. Cost</th>
            </tr>
          </thead>
          <tbody className="text-muted-foreground">
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4">Support Bot</td>
              <td className="py-2 pr-4">1,247</td>
              <td className="py-2 pr-4">2,340</td>
              <td className="py-2">$42.30</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 pr-4">Sales Bot</td>
              <td className="py-2 pr-4">892</td>
              <td className="py-2 pr-4">1,890</td>
              <td className="py-2">$28.15</td>
            </tr>
            <tr>
              <td className="py-2 pr-4">FAQ Bot</td>
              <td className="py-2 pr-4">2,103</td>
              <td className="py-2 pr-4">980</td>
              <td className="py-2">$15.40</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 id="cost-estimation">Cost Estimation</h2>
      <p>
        Convio calculates estimated costs based on your configured model pricing. To set up accurate cost tracking:
      </p>
      <ol>
        <li>Go to <strong>Settings → AI Models</strong></li>
        <li>Verify the input and output price per 1K tokens for each model</li>
        <li>Costs are calculated automatically based on actual token usage</li>
      </ol>

      <DocCallout variant="warning" icon={AlertTriangle} title="Cost spikes">
        A sudden increase in token usage often indicates an agent stuck in a conversation loop or a knowledge base retrieval returning too much context. Check the per-agent breakdown to identify the source.
      </DocCallout>

      <h2 id="optimizing">Optimizing Token Usage</h2>
      <ul>
        <li><strong>Shorten system prompts:</strong> Every token in the prompt is multiplied across all conversations</li>
        <li><strong>Limit knowledge base context:</strong> Use the top-k setting to retrieve fewer chunks</li>
        <li><strong>Set max output tokens:</strong> Prevent excessively long responses</li>
        <li><strong>Prune conversation history:</strong> Limit context window to recent messages</li>
        <li><strong>Use cheaper models for simple tasks:</strong> Route FAQ queries to smaller models</li>
      </ul>

      <h2 id="next-steps">Next Steps</h2>
      <DocCardGrid columns={2}>
        <DocNextStepCard
          icon={BarChart3}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Per-Agent Analytics"
          href="/docs/per-agent-analytics"
        />
        <DocNextStepCard
          icon={TrendingUp}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Key Metrics"
          href="/docs/key-metrics"
        />
        <DocNextStepCard
          icon={Bot}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="AI Models"
          href="/docs/ai-models"
        />
        <DocNextStepCard
          icon={ArrowRight}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          title="Exporting Analytics"
          href="/docs/exporting-analytics"
        />
      </DocCardGrid>
    </DocContent>
  )
}
