export interface McpServerTemplate {
  id: string
  name: string
  description: string
  provider: string
  url: string
  authType: 'none' | 'header' | 'oauth'
  type: 'stdio' | 'streamable-http'
  command?: string
  args?: string[]
  category: 'apps' | 'data' | 'devtools' | 'custom'
  /** Shown in the add/edit form when authType is header — tells the user which header name to use. */
  headerHint?: string
  /** Template is listed but not yet enabled — shown with a "Coming soon" badge. */
  comingSoon?: boolean
}

export const mcpServerTemplates: McpServerTemplate[] = [
  {
    id: 'notion',
    name: 'Notion',
    description: 'Search, read, and create pages, databases, and comments in your Notion workspace.',
    provider: 'notion',
    url: 'https://mcp.notion.com/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'apps',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Manage repositories, issues, pull requests, and code reviews.',
    provider: 'github',
    url: 'https://api.githubcopilot.com/mcp/',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'devtools',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Track issues, projects, and team workflows.',
    provider: 'linear',
    url: 'https://mcp.linear.app/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'devtools',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages, read channels, and manage conversations.',
    provider: 'slack',
    url: 'https://mcp.slack.com/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'apps',
  },
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read and write files in a local directory (stdio).',
    provider: 'filesystem',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/path/to/dir'],
    authType: 'none',
    type: 'stdio',
    category: 'custom',
    comingSoon: true,
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Manage payments, subscriptions, customers, and invoices.',
    provider: 'stripe',
    url: 'https://mcp.stripe.com/mcp/',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'apps',
    comingSoon: true,
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    description: 'Read and write Gmail, Google Calendar, and Google Drive.',
    provider: 'google',
    url: 'https://mcp.googleapis.com',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'apps',
    comingSoon: true,
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Query and update bases, tables, records, and fields.',
    provider: 'airtable',
    url: 'https://mcp.airtable.com/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'apps',
    comingSoon: true,
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Manage products, orders, customers, and store data.',
    provider: 'shopify',
    url: 'https://mcp.shopify.com/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'apps',
    comingSoon: true,
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Manage tickets, users, and support workflows.',
    provider: 'zendesk',
    url: 'https://mcp.zendesk.com/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'apps',
    comingSoon: true,
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Search the web with Brave Search API.',
    provider: 'brave',
    url: 'https://api.search.brave.com/mcp',
    authType: 'header',
    type: 'streamable-http',
    category: 'data',
    headerHint: 'Uses X-Subscription-Token (not Bearer) — put it in Custom headers: X-Subscription-Token: YOUR_KEY',
    comingSoon: true,
  },
  {
    id: 'exa',
    name: 'Exa',
    description: 'Semantic web search and content extraction for AI agents.',
    provider: 'exa',
    url: 'https://mcp.exa.ai/mcp',
    authType: 'header',
    type: 'streamable-http',
    category: 'data',
    headerHint: 'Uses x-api-key (not Bearer) — put it in Custom headers: x-api-key: YOUR_KEY',
    comingSoon: true,
  },
  {
    id: 'tavily',
    name: 'Tavily',
    description: 'AI-optimized web search, crawling, and extraction.',
    provider: 'tavily',
    url: 'https://mcp.tavily.com/mcp',
    authType: 'header',
    type: 'streamable-http',
    category: 'data',
    headerHint: 'Uses tavily-api-key (not Bearer) — put it in Custom headers: tavily-api-key: YOUR_KEY',
    comingSoon: true,
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    description: 'Scrape, crawl, and extract structured data from any website.',
    provider: 'firecrawl',
    url: 'https://mcp.firecrawl.dev/mcp',
    authType: 'header',
    type: 'streamable-http',
    category: 'data',
    comingSoon: true,
  },
  {
    id: 'fetch',
    name: 'Fetch',
    description: 'Fetch and summarize content from URLs (stdio).',
    provider: 'fetch',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    authType: 'none',
    type: 'stdio',
    category: 'data',
    comingSoon: true,
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Query and manage a PostgreSQL database (stdio).',
    provider: 'postgresql',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres', 'postgresql://localhost:5432/mydb'],
    authType: 'none',
    type: 'stdio',
    category: 'data',
    comingSoon: true,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage DNS, workers, KV, and Cloudflare resources.',
    provider: 'cloudflare',
    url: 'https://mcp.cloudflare.com/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'devtools',
    comingSoon: true,
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Manage repositories, merge requests, issues, and pipelines.',
    provider: 'gitlab',
    url: 'https://gitlab.com/mcp/server',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'devtools',
    comingSoon: true,
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Query issues, releases, and error data from Sentry.',
    provider: 'sentry',
    url: 'https://mcp.sentry.dev/mcp',
    authType: 'oauth',
    type: 'streamable-http',
    category: 'devtools',
    comingSoon: true,
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Query and manage your Supabase projects and databases.',
    provider: 'supabase',
    url: 'https://mcp.supabase.com',
    authType: 'header',
    type: 'streamable-http',
    category: 'devtools',
    comingSoon: true,
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Browser automation for testing and web scraping (stdio).',
    provider: 'playwright',
    command: 'npx',
    args: ['-y', '@playwright/mcp@latest'],
    authType: 'none',
    type: 'stdio',
    category: 'devtools',
    comingSoon: true,
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'Persistent knowledge-graph memory for agents (stdio).',
    provider: 'memory',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    authType: 'none',
    type: 'stdio',
    category: 'custom',
    comingSoon: true,
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Headless browser automation for the web (stdio).',
    provider: 'puppeteer',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    authType: 'none',
    type: 'stdio',
    category: 'custom',
    comingSoon: true,
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Query and manage a local SQLite database (stdio).',
    provider: 'sqlite',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite', '/path/to/database.db'],
    authType: 'none',
    type: 'stdio',
    category: 'data',
    comingSoon: true,
  },
]
