import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/server.ts'],
  format: 'cjs',
  platform: 'node',
  target: 'node22',
  outDir: 'dist',
  clean: true,
  sourcemap: true,
  shims: true,
  splitting: false,
  outExtension: ({ format }) => format === 'cjs' ? '.cjs' : '.js',
  noExternal: ['@convio/ai', '@convio/config', '@convio/database', '@convio/types', '@convio/validation'],
  external: [
    'fastify',
    'fastify-plugin',
    '@fastify/cors',
    '@fastify/error',
    '@fastify/formbody',
    '@fastify/helmet',
    '@fastify/multipart',
    '@fastify/rate-limit',
    '@fastify/swagger',
    '@fastify/swagger-ui',
    '@fastify/type-provider-typebox',
    'pg',
    'pg-native',
    'pgpass',
    '@prisma/client',
    '@prisma/adapter-pg',
    '@prisma/driver-adapter-utils',
    '@huggingface/transformers',
  ],
})
